apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-rs
  # namespace: prod-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: hr-app
          image: saimanoj143/cap-hrr-app:v1.1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "production"
            - name: PORT
              value: "5000"
            - name: HOST
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "production" 
---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
