apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-rs
  # namespace: prod-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: hr-app
          image: saimanoj143/cap-hrr-app:v1.1.0
          ports:
            - containerPort: 3000
          env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: hr-app-secrets
              key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
